name: Delete

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 3'

env:
  DELETE_ARTIFACTS: true

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      if: env.DELETE_ARTIFACTS == 'true'
      with:
        token: ${{ secrets.RELEASES_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
