name: Delete Older

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 3'

env:
  DELETE_ARTIFACTS: true
  KEEP_DAY: 0
  KEEP_MININUM_RUNS: 0

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Delete older workflow runs and artifacts
      uses: Mattraks/delete-workflow-runs@main
      if: env.DELETE_ARTIFACTS == 'true'
      with:
        token: ${{ secrets.RELEASES_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: ${{ env.KEEP_DAY }}
        keep_minimum_runs: ${{ env.KEEP_MININUM_RUNS }}

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 1
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
