name: Delete

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 3'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.RELEASES_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0

    - name: Remove Releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 2
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}