name: Test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  UPLOAD_COWTRANSFER: false
  RELEASE: true
  TZ: Asia/Taipei
  FILE_NAME: OpenWrt-S905X3

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Push Tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +"%m%d%Y%H")"

    - name: Create release
      id: release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.FILE_NAME }}
        allowUpdates: true
        tag: ${{ steps.tag.outputs.release_tag }}
        commit: main
        token: ${{ secrets.RELEASES_TOKEN }}
        body: |
          Default IP：192.168.0.254
          Default PW： password
          ${{ env.useVersionInfo }}
        artifacts: ${{ env.FIRMWARE }}/*